server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
#  application:
#    name: tool
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB